# Generated by Django 2.2.6 on 2019-10-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingitem',
            old_name='list_id',
            new_name='list_name',
        ),
        migrations.RemoveField(
            model_name='shoppingitem',
            name='date_created',
        ),
        migrations.AlterField(
            model_name='shoppingitem',
            name='quantity',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
