# Generated by Django 2.2.6 on 2019-10-04 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191003_0335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingitem',
            name='id',
        ),
        migrations.RemoveField(
            model_name='shoppingitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='bought',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='item_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
