# Generated by Django 2.2.6 on 2019-10-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191004_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='minimum_refill_level',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='warning_message',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
