# Generated by Django 2.2.6 on 2019-10-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191004_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitem',
            name='item_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
